# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vtn_principal.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_vtn_principal(object):
    def setupUi(self, vtn_principal):
        if not vtn_principal.objectName():
            vtn_principal.setObjectName(u"vtn_principal")
        vtn_principal.resize(800, 243)
        self.centralwidget = QWidget(vtn_principal)
        self.centralwidget.setObjectName(u"centralwidget")
        self.txt_nombre = QLineEdit(self.centralwidget)
        self.txt_nombre.setObjectName(u"txt_nombre")
        self.txt_nombre.setGeometry(QRect(220, 20, 191, 21))
        self.txt_nombre.setMaxLength(50)
        self.txt_cedula = QLineEdit(self.centralwidget)
        self.txt_cedula.setObjectName(u"txt_cedula")
        self.txt_cedula.setGeometry(QRect(610, 20, 181, 21))
        self.txt_cedula.setMaxLength(10)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(370, 120, 47, 13))
        self.txt_correo = QLineEdit(self.centralwidget)
        self.txt_correo.setObjectName(u"txt_correo")
        self.txt_correo.setGeometry(QRect(610, 50, 181, 20))
        self.txt_correo.setMaxLength(50)
        self.txt_telefono = QLineEdit(self.centralwidget)
        self.txt_telefono.setObjectName(u"txt_telefono")
        self.txt_telefono.setGeometry(QRect(220, 50, 191, 20))
        self.txt_telefono.setMaxLength(10)
        self.lbl_nombre = QLabel(self.centralwidget)
        self.lbl_nombre.setObjectName(u"lbl_nombre")
        self.lbl_nombre.setGeometry(QRect(20, 20, 191, 21))
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.lbl_nombre.setFont(font)
        self.lbl_telefono_2 = QLabel(self.centralwidget)
        self.lbl_telefono_2.setObjectName(u"lbl_telefono_2")
        self.lbl_telefono_2.setGeometry(QRect(120, 50, 91, 20))
        self.lbl_telefono_2.setFont(font)
        self.lbl_cedula = QLabel(self.centralwidget)
        self.lbl_cedula.setObjectName(u"lbl_cedula")
        self.lbl_cedula.setGeometry(QRect(420, 20, 181, 20))
        self.lbl_cedula.setFont(font)
        self.lbl_correo = QLabel(self.centralwidget)
        self.lbl_correo.setObjectName(u"lbl_correo")
        self.lbl_correo.setGeometry(QRect(530, 50, 71, 20))
        self.lbl_correo.setFont(font)
        self.btn_eliminar = QPushButton(self.centralwidget)
        self.btn_eliminar.setObjectName(u"btn_eliminar")
        self.btn_eliminar.setGeometry(QRect(400, 160, 75, 31))
        self.btn_agregar = QPushButton(self.centralwidget)
        self.btn_agregar.setObjectName(u"btn_agregar")
        self.btn_agregar.setGeometry(QRect(240, 160, 75, 31))
        self.btn_actualizar = QPushButton(self.centralwidget)
        self.btn_actualizar.setObjectName(u"btn_actualizar")
        self.btn_actualizar.setGeometry(QRect(320, 160, 75, 31))
        self.btn_limpiar = QPushButton(self.centralwidget)
        self.btn_limpiar.setObjectName(u"btn_limpiar")
        self.btn_limpiar.setGeometry(QRect(480, 160, 75, 31))
        self.txt_buscar_cedula = QLineEdit(self.centralwidget)
        self.txt_buscar_cedula.setObjectName(u"txt_buscar_cedula")
        self.txt_buscar_cedula.setGeometry(QRect(350, 120, 191, 31))
        self.txt_buscar_cedula.setMaxLength(50)
        self.btn_buscar = QPushButton(self.centralwidget)
        self.btn_buscar.setObjectName(u"btn_buscar")
        self.btn_buscar.setGeometry(QRect(550, 120, 75, 31))
        self.lbl_buscar_cedula = QLabel(self.centralwidget)
        self.lbl_buscar_cedula.setObjectName(u"lbl_buscar_cedula")
        self.lbl_buscar_cedula.setGeometry(QRect(180, 120, 171, 31))
        self.lbl_buscar_cedula.setFont(font)
        self.cb_tipo_sala = QComboBox(self.centralwidget)
        self.cb_tipo_sala.addItem("")
        self.cb_tipo_sala.addItem("")
        self.cb_tipo_sala.addItem("")
        self.cb_tipo_sala.addItem("")
        self.cb_tipo_sala.addItem("")
        self.cb_tipo_sala.addItem("")
        self.cb_tipo_sala.addItem("")
        self.cb_tipo_sala.setObjectName(u"cb_tipo_sala")
        self.cb_tipo_sala.setGeometry(QRect(420, 80, 191, 22))
        self.lbl_tipo_sala = QLabel(self.centralwidget)
        self.lbl_tipo_sala.setObjectName(u"lbl_tipo_sala")
        self.lbl_tipo_sala.setGeometry(QRect(300, 80, 121, 20))
        self.lbl_tipo_sala.setFont(font)
        vtn_principal.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(vtn_principal)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        vtn_principal.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(vtn_principal)
        self.statusbar.setObjectName(u"statusbar")
        vtn_principal.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.txt_nombre, self.txt_telefono)
        QWidget.setTabOrder(self.txt_telefono, self.txt_cedula)
        QWidget.setTabOrder(self.txt_cedula, self.txt_correo)
        QWidget.setTabOrder(self.txt_correo, self.cb_tipo_sala)
        QWidget.setTabOrder(self.cb_tipo_sala, self.txt_buscar_cedula)
        QWidget.setTabOrder(self.txt_buscar_cedula, self.btn_buscar)
        QWidget.setTabOrder(self.btn_buscar, self.btn_agregar)
        QWidget.setTabOrder(self.btn_agregar, self.btn_actualizar)
        QWidget.setTabOrder(self.btn_actualizar, self.btn_eliminar)
        QWidget.setTabOrder(self.btn_eliminar, self.btn_limpiar)

        self.retranslateUi(vtn_principal)

        QMetaObject.connectSlotsByName(vtn_principal)
    # setupUi

    def retranslateUi(self, vtn_principal):
        vtn_principal.setWindowTitle(QCoreApplication.translate("vtn_principal", u"Sistema de Adminitraci\u00f3n de Cine", None))
        self.label.setText("")
        self.lbl_nombre.setText(QCoreApplication.translate("vtn_principal", u"Nombre del Cliente:", None))
        self.lbl_telefono_2.setText(QCoreApplication.translate("vtn_principal", u"Telefono:", None))
        self.lbl_cedula.setText(QCoreApplication.translate("vtn_principal", u"Cedula del Cliente:", None))
        self.lbl_correo.setText(QCoreApplication.translate("vtn_principal", u"Correo:", None))
#if QT_CONFIG(tooltip)
        self.btn_eliminar.setToolTip(QCoreApplication.translate("vtn_principal", u"Borra el formulario", None))
#endif // QT_CONFIG(tooltip)
        self.btn_eliminar.setText(QCoreApplication.translate("vtn_principal", u"Eliminar", None))
#if QT_CONFIG(tooltip)
        self.btn_agregar.setToolTip(QCoreApplication.translate("vtn_principal", u"Guardar los datos del titular", None))
#endif // QT_CONFIG(tooltip)
        self.btn_agregar.setText(QCoreApplication.translate("vtn_principal", u"Agregar", None))
#if QT_CONFIG(tooltip)
        self.btn_actualizar.setToolTip(QCoreApplication.translate("vtn_principal", u"Guardar los datos del titular", None))
#endif // QT_CONFIG(tooltip)
        self.btn_actualizar.setText(QCoreApplication.translate("vtn_principal", u"Actualizar", None))
#if QT_CONFIG(tooltip)
        self.btn_limpiar.setToolTip(QCoreApplication.translate("vtn_principal", u"Borra el formulario", None))
#endif // QT_CONFIG(tooltip)
        self.btn_limpiar.setText(QCoreApplication.translate("vtn_principal", u"Limpiar", None))
#if QT_CONFIG(tooltip)
        self.btn_buscar.setToolTip(QCoreApplication.translate("vtn_principal", u"Borra el formulario", None))
#endif // QT_CONFIG(tooltip)
        self.btn_buscar.setText(QCoreApplication.translate("vtn_principal", u"Buscar", None))
        self.lbl_buscar_cedula.setText(QCoreApplication.translate("vtn_principal", u"BuscarPorCedula:", None))
        self.cb_tipo_sala.setItemText(0, QCoreApplication.translate("vtn_principal", u"Seleccionar", None))
        self.cb_tipo_sala.setItemText(1, QCoreApplication.translate("vtn_principal", u"2D", None))
        self.cb_tipo_sala.setItemText(2, QCoreApplication.translate("vtn_principal", u"3D", None))
        self.cb_tipo_sala.setItemText(3, QCoreApplication.translate("vtn_principal", u"IMAX", None))
        self.cb_tipo_sala.setItemText(4, QCoreApplication.translate("vtn_principal", u"7D", None))
        self.cb_tipo_sala.setItemText(5, QCoreApplication.translate("vtn_principal", u"Screen X", None))
        self.cb_tipo_sala.setItemText(6, QCoreApplication.translate("vtn_principal", u"VIP", None))

        self.lbl_tipo_sala.setText(QCoreApplication.translate("vtn_principal", u"TipoDeSala:", None))
    # retranslateUi

